SUBROUTINE TOTO_OPENACC (A, KLON, YDSTACK)
  
!$acc routine( TOTO_OPENACC ) seq
  
  USE STACK_MOD
#include "stack.h"
  
  IMPLICIT NONE
  
  INTEGER :: KIDIA
  INTEGER :: KFDIA
  INTEGER, INTENT(IN) :: KLON
  REAL, INTENT(INOUT) :: A(KLON)
  REAL :: TOTO
  INTEGER :: JLON
  JLON=KIDIA
  TYPE(STACK), INTENT(IN) :: YDSTACK
  TYPE(STACK) :: YLSTACK
  YLSTACK = YDSTACK
  JLON=KIDIA
  
  TOTO = 0.0
  DO JLON=KIDIA,KFDIA
    A(JLON) = 2.0
  END DO
  
END SUBROUTINE TOTO_OPENACC
